# Generated by Django 4.1.10 on 2024-01-23 06:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_orders', models.IntegerField(default=0)),
                ('no_of_b2b', models.IntegerField(default=0)),
                ('no_of_b2c', models.IntegerField(default=0)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_no', models.CharField(default='', max_length=15)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('website_link', models.CharField(default='', max_length=100)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 1, 23, 6, 19, 28, 549872))),
                ('payment_mode', models.CharField(choices=[('BANK', 'BANK'), ('CASH', 'CASH'), ('UPI', 'UPI')], default='BANK', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='courier_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('CASE', 'CASE')], default='CREDIT', max_length=20)),
                ('order_mode', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2C', max_length=10)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_value', models.FloatField(default=0.0)),
                ('cod_value', models.FloatField(default=0.0)),
                ('payment_mode', models.CharField(choices=[('PREPAID', 'PREPAID'), ('COD', 'COD')], default='PREPAID', max_length=20)),
                ('awb_no', models.CharField(blank=True, max_length=20, null=True)),
                ('shipped_to_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shipped_to_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('shipped_to_city', models.CharField(blank=True, max_length=30, null=True)),
                ('shipped_to_state', models.CharField(blank=True, max_length=30, null=True)),
                ('shipment_status', models.CharField(choices=[('IN TRANSIT', 'IN TRANSIT'), ('DELIVERED', 'DELIVERED'), ('RTO IN TRANSIT', 'RTO IN TRANSIT'), ('RTO IN DELIVERED', 'RTO IN DELIVERED')], default='IN TRANSIT', max_length=20)),
                ('no_of_box', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, default=1.0, null=True)),
                ('apply_weight', models.FloatField(blank=True, null=True)),
                ('charged_weight', models.FloatField(blank=True, null=True)),
                ('freight_amount', models.FloatField(default=0.0)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('receipt_upload', models.ImageField(blank=True, null=True, upload_to='orderReciept/')),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='o_customer', to='courier_app.customer')),
                ('service_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='o_service_provider', to='courier_app.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_ledger', to='courier_app.bill')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_ledger', to='courier_app.payment')),
            ],
        ),
        migrations.CreateModel(
            name='FrieghtRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('north_rate', models.FloatField(blank=True, null=True)),
                ('south_rate', models.FloatField(blank=True, null=True)),
                ('east_rate', models.FloatField(blank=True, null=True)),
                ('west_rate', models.FloatField(blank=True, null=True)),
                ('special_destination', models.FloatField(blank=True, null=True)),
                ('within_zone', models.FloatField(blank=True, null=True)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ft_customer', to='courier_app.customer')),
                ('service_Provider_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ft_service_provider', to='courier_app.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_app.customer'),
        ),
    ]
