# Generated by Django 4.1.10 on 2024-01-23 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 6, 20, 4, 367028)),
        ),
    ]
