# Generated by Django 4.1.10 on 2024-01-23 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0004_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 9, 56, 52, 362216)),
        ),
    ]
