# Generated by Django 4.1.10 on 2024-01-24 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0005_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 32, 37, 737147)),
        ),
    ]
