# Generated by Django 4.1.10 on 2024-02-08 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0006_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_zone', models.CharField(choices=[('NORTH ZONE', 'NORTH ZONE'), ('SOUTH ZONE', 'SOUTH ZONE'), ('EAST ZONE', 'EAST ZONE'), ('WEST ZONE', 'WEST ZONE'), ('SPECIAL DESTINATION', 'SPECIAL DESTINATION'), ('WITHIN ZONE', 'WITHIN ZONE')], default='WITHIN ZONE', max_length=30)),
                ('north_rate', models.FloatField(blank=True, null=True)),
                ('south_rate', models.FloatField(blank=True, null=True)),
                ('east_rate', models.FloatField(blank=True, null=True)),
                ('west_rate', models.FloatField(blank=True, null=True)),
                ('special_dest_rate', models.FloatField(blank=True, null=True)),
                ('within_zone_rate', models.FloatField(blank=True, null=True)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ft_customer', to='courier_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fsc', models.FloatField(default=0.0)),
                ('fov', models.FloatField(default=0.0)),
                ('docket', models.FloatField(default=0.0)),
                ('date_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('NORTH ZONE', 'NORTH ZONE'), ('SOUTH ZONE', 'SOUTH ZONE'), ('EAST ZONE', 'EAST ZONE'), ('WEST ZONE', 'WEST ZONE'), ('SPECIAL DESTINATION', 'SPECIAL DESTINATION'), ('WITHIN ZONE', 'WITHIN ZONE')], default='WITHIN ZONE', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('date_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='basic_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='from_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 12, 2, 58, 28220)),
        ),
        migrations.DeleteModel(
            name='FrieghtRate',
        ),
    ]
