# Generated by Django 4.1.10 on 2024-04-01 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0010_bill_basic_amount_order_bill_id_order_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_mode', models.CharField(choices=[('BANK', 'BANK'), ('CASH', 'CASH'), ('UPI', 'UPI')], default='BANK', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('reciept_upload', models.ImageField(blank=True, null=True, upload_to='codPaymentReciept/')),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_cod_payment', to='courier_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_app.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_cod_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.bill'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('CASH', 'CASH')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('PREPAID', 'PREPAID'), ('COD', 'COD'), ('TO PAY', 'TO PAY')], default='PREPAID', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderCodPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cod_payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.codpayment')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.customer')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='CashBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('counter', models.CharField(default='', max_length=50)),
                ('order_mode', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2C', max_length=10)),
                ('deliver_mode', models.CharField(choices=[('AIR', 'AIR'), ('SURFACE', 'SURFACE'), ('PREMIUM', 'PREMIUM')], default='SURFACE', max_length=30)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_value', models.FloatField(default=0.0)),
                ('cod_value', models.FloatField(default=0.0)),
                ('payment_mode', models.CharField(choices=[('PREPAID', 'PREPAID'), ('COD', 'COD'), ('TO PAY', 'TO PAY')], default='PREPAID', max_length=20)),
                ('awb_no', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=30, null=True)),
                ('origin_state', models.CharField(blank=True, max_length=30, null=True)),
                ('consignee', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=30, null=True)),
                ('destination_state', models.CharField(blank=True, max_length=30, null=True)),
                ('shipment_status', models.CharField(choices=[('IN TRANSIT', 'IN TRANSIT'), ('DELIVERED', 'DELIVERED'), ('RTO IN TRANSIT', 'RTO IN TRANSIT'), ('RTO DELIVERED', 'RTO DELIVERED')], default='IN TRANSIT', max_length=20)),
                ('no_of_box', models.IntegerField(blank=True, null=True)),
                ('charged_weight', models.FloatField(blank=True, null=True)),
                ('freight_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('receipt_upload', models.ImageField(blank=True, null=True, upload_to='orderReciept/')),
                ('is_bill_generated', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Billed', 'Billed'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('date_create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.bill')),
                ('service_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cash_service_provider', to='courier_app.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_app.bill')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_app.customer')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier_app.payment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cod_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.codpayment'),
        ),
    ]
