# Generated by Django 4.1.10 on 2024-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0011_codpayment_bill_payment_id_order_balance_cod_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbooking',
            name='mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK'), ('UPI', 'UPI')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='mannual_frieght',
            field=models.FloatField(default=0.0),
        ),
    ]
